---
- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm using Helm install script
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
    creates: /usr/local/bin/helm
