---
- name: Set up development environment
  hosts: local
  gather_facts: false
  become: true
  roles:
    - gitconfig
    - common
    - snaps
    - kubectl
    - k9s
    - helm
    - terraform
    - argocd
    - bashrc
    - tmux
    - docker