bashrc_aliases:
  - line: "source <(kubectl completion bash)"
  - line: "alias d='docker'"
  - line: "alias dc='docker compose'"
  - line: "alias k='kubectl'"
  - line: "alias h='helm'"
  - line: "alias tf='terraform'"
  - line: "alias a='argocd'"
  - line: "alias c='code'"
  - line: "alias refresh='source ~/.bashrc && hash -r && clear'"
  - line: "complete -F __start_kubectl k"