---
- name: Get latest stable kubectl release
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_release
  changed_when: false

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_release.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    owner: root
    group: root

